name: Port Checker Autograding

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set permission
        run: chmod +x port_checker.sh
      
      - name: Run port checker
        run: bash port_checker.sh
