name: Autograding

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Debug list files
        run: ls -l
      
      - name: Set permission
        run: chmod +x backup.sh
      
      - name: Run backup script
        run: |
          mkdir Documents
          echo "file1" > Documents/file1.txt
          bash backup.sh
          test -f backup/file1.txt

